# This is a basic workflow to help you get started with Actions

name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install npm stuff
        run: npm ci
      - name: Run eslint
        run: npx eslint --max-warnings 0 ./
  texture_atlas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install npm stuff
        run: npm ci
      - name: Generate atlas
        run: node ./scripts/make_atlas.js
  build_libs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install npm stuff
        run: npm ci
      - name: Run build_libs.sh
        run: |
          chmod +x ./scripts/build_libs.sh
          ./scripts/build_libs.sh

